version: 2

updates:
  - package-ecosystem: cargo
    groups:
      rust:
        patterns: ['*']
    directory: '/'
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    groups:
      gha:
        patterns: ['*']
    directory: '/'
    schedule:
      interval: monthly
