-- do not edit manually!
return { setup = function()
vim.api.nvim_set_hl(0, 'Normal', { force = true, fg = '#afbbd3', ctermfg = 146, bg = '#202632', ctermbg = 235 })
vim.api.nvim_set_hl(0, 'Comment', { force = true, fg = '#6c7588', ctermfg = 243 })
vim.api.nvim_set_hl(0, 'String', { force = true, fg = '#7db349', ctermfg = 107 })
vim.api.nvim_set_hl(0, 'Character', { force = true, link = 'String' })
vim.api.nvim_set_hl(0, 'Constant', { force = true, fg = '#cd9600', ctermfg = 172 })
vim.api.nvim_set_hl(0, 'Identifier', { force = true, fg = '#afbbd3', ctermfg = 146 })
vim.api.nvim_set_hl(0, 'Function', { force = true, fg = '#50a5fa', ctermfg = 75 })
vim.api.nvim_set_hl(0, 'Statement', { force = true, fg = '#ef7675', ctermfg = 210, italic = true })
vim.api.nvim_set_hl(0, 'Operator', { force = true, fg = '#6c7588', ctermfg = 243 })
vim.api.nvim_set_hl(0, 'Delimiter', { force = true, link = 'Operator' })
vim.api.nvim_set_hl(0, 'Type', { force = true, fg = '#00bcc0', ctermfg = 37 })
vim.api.nvim_set_hl(0, 'Special', { force = true, fg = '#afbbd3', ctermfg = 146 })
vim.api.nvim_set_hl(0, 'PreProc', { force = true, link = 'Statement' })
vim.api.nvim_set_hl(0, 'Title', { force = true, fg = '#76a5d7', ctermfg = 110, bold = true })
vim.api.nvim_set_hl(0, 'Todo', { force = true, fg = '#202632', ctermfg = 235, bg = '#00bcc0', ctermbg = 37, bold = true })
vim.api.nvim_set_hl(0, 'LineNr', { force = true, fg = '#3a414f', ctermfg = 238 })
vim.api.nvim_set_hl(0, 'CursorLineNr', { force = true, fg = '#6c7588', ctermfg = 243, bold = true })
vim.api.nvim_set_hl(0, 'Whitespace', { force = true, fg = '#3a414f', ctermfg = 238 })
vim.api.nvim_set_hl(0, 'CursorLine', { force = true, bg = '#272d39', ctermbg = 236 })
vim.api.nvim_set_hl(0, 'CursorColumn', { force = true, link = 'CursorLine' })
vim.api.nvim_set_hl(0, 'StatusLine', { force = true, fg = '#afbbd3', ctermfg = 146, bg = '#3a414f', ctermbg = 238 })
vim.api.nvim_set_hl(0, 'StatusLineNC', { force = true, fg = '#8691a6', ctermfg = 103, bg = '#3a414f', ctermbg = 238 })
vim.api.nvim_set_hl(0, 'TabLine', { force = true, bg = '#29384d', ctermbg = 237 })
vim.api.nvim_set_hl(0, 'TabLineFill', { force = true, link = 'TabLine' })
vim.api.nvim_set_hl(0, 'TabLineSel', { force = true, fg = '#afbbd3', ctermfg = 146, bg = '#202632', ctermbg = 235, bold = true })
vim.api.nvim_set_hl(0, 'WinBar', { force = true, fg = '#6c7588', ctermfg = 243, bg = '#202632', ctermbg = 235 })
vim.api.nvim_set_hl(0, 'WinBarNC', { force = true, link = 'WinBar' })
vim.api.nvim_set_hl(0, 'WinSeparator', { force = true, fg = '#3a414f', ctermfg = 238 })
vim.api.nvim_set_hl(0, 'Visual', { force = true, bg = '#2d384a', ctermbg = 237 })
vim.api.nvim_set_hl(0, 'Search', { force = true, bg = '#2f4765', ctermbg = 238 })
vim.api.nvim_set_hl(0, 'CurSearch', { force = true, fg = '#202632', ctermfg = 235, bg = '#50a5fa', ctermbg = 75, bold = true })
vim.api.nvim_set_hl(0, 'Directory', { force = true, fg = '#76a5d7', ctermfg = 110 })
vim.api.nvim_set_hl(0, 'MoreMsg', { force = true, fg = '#76a5d7', ctermfg = 110 })
vim.api.nvim_set_hl(0, 'Question', { force = true, link = 'MoreMsg' })
vim.api.nvim_set_hl(0, 'ModeMsg', { force = true, fg = '#8691a6', ctermfg = 103 })
vim.api.nvim_set_hl(0, 'NonText', { force = true, fg = '#3a414f', ctermfg = 238 })
vim.api.nvim_set_hl(0, 'NormalFloat', { force = true, bg = '#252c38', ctermbg = 235 })
vim.api.nvim_set_hl(0, 'FloatBorder', { force = true, fg = '#575f70', ctermfg = 59, bg = '#232a36', ctermbg = 235 })
vim.api.nvim_set_hl(0, 'FloatTitle', { force = true, fg = '#6c7588', ctermfg = 243, bg = '#242b37', ctermbg = 235, bold = true })
vim.api.nvim_set_hl(0, 'Pmenu', { force = true, link = 'NormalFloat' })
vim.api.nvim_set_hl(0, 'PmenuSel', { force = true, link = 'Visual' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { force = true, bg = '#6c7588', ctermbg = 243 })
vim.api.nvim_set_hl(0, 'Error', { force = true, fg = '#ef7675', ctermfg = 210, bold = true })
vim.api.nvim_set_hl(0, 'ErrorMsg', { force = true, fg = '#ef7675', ctermfg = 210, bold = true })
vim.api.nvim_set_hl(0, 'WarningMsg', { force = true, fg = '#cd9600', ctermfg = 172, bold = true })
vim.api.nvim_set_hl(0, 'DiagnosticOk', { force = true, fg = '#7db349', ctermfg = 107 })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { force = true, fg = '#50a5fa', ctermfg = 75 })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { force = true, fg = '#00bcc0', ctermfg = 37 })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { force = true, fg = '#cd9600', ctermfg = 172 })
vim.api.nvim_set_hl(0, 'DiagnosticError', { force = true, fg = '#ef7675', ctermfg = 210 })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk', { force = true, sp = '#7db349', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { force = true, sp = '#50a5fa', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { force = true, sp = '#00bcc0', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { force = true, sp = '#cd9600', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { force = true, sp = '#ef7675', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextOk', { force = true, fg = '#7db349', ctermfg = 107, bg = '#283236', ctermbg = 236 })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { force = true, fg = '#50a5fa', ctermfg = 75, bg = '#253142', ctermbg = 236 })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', { force = true, fg = '#00bcc0', ctermfg = 37, bg = '#22323e', ctermbg = 236 })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { force = true, fg = '#cd9600', ctermfg = 172, bg = '#2e3034', ctermbg = 236 })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { force = true, fg = '#ef7675', ctermfg = 210, bg = '#322e39', ctermbg = 236 })
vim.api.nvim_set_hl(0, 'SpellLocal', { force = true, link = 'DiagnosticUnderlineHint' })
vim.api.nvim_set_hl(0, 'SpellRare', { force = true, link = 'DiagnosticUnderlineInfo' })
vim.api.nvim_set_hl(0, 'SpellCap', { force = true, link = 'DiagnosticUnderlineWarn' })
vim.api.nvim_set_hl(0, 'SpellBad', { force = true, link = 'DiagnosticUnderlineError' })
vim.api.nvim_set_hl(0, 'MatchParen', { force = true, fg = '#afbbd3', ctermfg = 146, bg = '#2f3643', ctermbg = 236, bold = true })
vim.api.nvim_set_hl(0, 'IlluminatedWordText', { force = true, bg = '#2f3643', ctermbg = 236 })
vim.api.nvim_set_hl(0, 'IlluminatedWordRead', { force = true, link = 'IlluminatedWordText' })
vim.api.nvim_set_hl(0, 'IlluminatedWordWrite', { force = true, link = 'IlluminatedWordText' })
vim.api.nvim_set_hl(0, 'Added', { force = true, fg = '#7db349', ctermfg = 107 })
vim.api.nvim_set_hl(0, 'Removed', { force = true, fg = '#ef7675', ctermfg = 210 })
vim.api.nvim_set_hl(0, 'Changed', { force = true, fg = '#50a5fa', ctermfg = 75 })
vim.api.nvim_set_hl(0, 'DiffAdd', { force = true, bg = '#2d3a39', ctermbg = 237 })
vim.api.nvim_set_hl(0, 'DiffDelete', { force = true, bg = '#3d333d', ctermbg = 237 })
vim.api.nvim_set_hl(0, 'DiffChange', { force = true, bg = '#29384d', ctermbg = 237 })
vim.api.nvim_set_hl(0, 'DiffText', { force = true, bg = '#304969', ctermbg = 238 })
vim.api.nvim_set_hl(0, 'GitSignsStagedAdd', { force = true, link = 'GitSignsAdd' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChange', { force = true, link = 'GitSignsChange' })
vim.api.nvim_set_hl(0, 'GitSignsStagedDelete', { force = true, link = 'GitSignsDelete' })
vim.api.nvim_set_hl(0, 'GitSignsAddInline', { force = true, bg = '#394e3f', ctermbg = 238 })
vim.api.nvim_set_hl(0, 'GitSignsDeleteInline', { force = true, bg = '#5a3f47', ctermbg = 238 })
vim.api.nvim_set_hl(0, 'GitSignsChangeInline', { force = true, bg = '#394e3f', ctermbg = 238 })
vim.api.nvim_set_hl(0, 'gitcommitHeader', { force = true, link = 'Title' })
vim.api.nvim_set_hl(0, 'gitcommitSummary', { force = true, link = 'Title' })
vim.api.nvim_set_hl(0, 'diffLine', { force = true, link = 'Comment' })
vim.api.nvim_set_hl(0, 'diffSubname', { force = true, link = 'Title' })
vim.api.nvim_set_hl(0, 'diffNewFile', { force = true, link = 'Added' })
vim.api.nvim_set_hl(0, 'diffOldFile', { force = true, link = 'Removed' })
vim.api.nvim_set_hl(0, 'diffIndexLine', { force = true, link = 'Comment' })
vim.api.nvim_set_hl(0, '@variable', { force = true, fg = '#afbbd3', ctermfg = 146 })
vim.api.nvim_set_hl(0, '@property', { force = true, fg = '#a68cf4', ctermfg = 141 })
vim.api.nvim_set_hl(0, '@string.special.url', { force = true, fg = '#50a5fa', ctermfg = 75, underline = true })
vim.api.nvim_set_hl(0, '@markup.link', { force = true, fg = '#50a5fa', ctermfg = 75 })
vim.api.nvim_set_hl(0, '@markup.link.label', { force = true, fg = '#50a5fa', ctermfg = 75, underdashed = true })
vim.api.nvim_set_hl(0, '@markup.quote', { force = true, fg = '#8691a6', ctermfg = 103 })
vim.api.nvim_set_hl(0, '@markup.raw', { force = true, fg = '#a396d4', ctermfg = 140 })
vim.api.nvim_set_hl(0, '@attribute.builtin', { force = true, link = '@attribute' })
vim.api.nvim_set_hl(0, '@constant.builtin', { force = true, link = '@constant' })
vim.api.nvim_set_hl(0, '@function.builtin', { force = true, link = '@function' })
vim.api.nvim_set_hl(0, '@type.builtin', { force = true, link = '@type' })
vim.api.nvim_set_hl(0, '@constructor', { force = true, link = '@function' })
vim.api.nvim_set_hl(0, '@keyword.conditional.ternary', { force = true, link = '@operator' })
vim.api.nvim_set_hl(0, '@markup.link.url', { force = true, link = '@string.special.url' })
vim.api.nvim_set_hl(0, '@variable.member', { force = true, link = '@property' })
vim.api.nvim_set_hl(0, '@attribute.python', { force = true, link = '@function' })
vim.api.nvim_set_hl(0, '@constructor.lua', { force = true, link = '@punctuation' })
vim.api.nvim_set_hl(0, '@keyword.vim', { force = true, link = '@function' })
vim.api.nvim_set_hl(0, '@lsp.type.decorator', { force = true, link = '@lsp.type.function' })
vim.api.nvim_set_hl(0, '@lsp.type.enumMember', { force = true, link = '@lsp.type.property' })
vim.api.nvim_set_hl(0, '@lsp.type.macro', { force = true, link = '@function.macro' })
vim.api.nvim_set_hl(0, '@lsp.type.typeAlias', { force = true, link = '@lsp.type.type' })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { force = true, fg = '#50a5fa', ctermfg = 75, bold = true })
vim.api.nvim_set_hl(0, 'TelescopeNormal', { force = true, link = 'NormalFloat' })
vim.api.nvim_set_hl(0, 'TelescopeTitle', { force = true, link = 'FloatTitle' })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { force = true, link = 'FloatBorder' })
vim.api.nvim_set_hl(0, 'CmpItemAbbr', { force = true, fg = '#96a1b7', ctermfg = 109 })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { force = true, fg = '#50a5fa', ctermfg = 75, bold = true })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { force = true, fg = '#76a5d7', ctermfg = 110 })
vim.api.nvim_set_hl(0, 'CmpItemKind', { force = true, fg = '#a68cf4', ctermfg = 141 })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { force = true, link = 'Constant' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { force = true, link = 'Type' })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { force = true, link = 'Function' })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { force = true, link = 'Type' })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { force = true, link = 'Constant' })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { force = true, link = 'Function' })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { force = true, link = 'Type' })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { force = true, link = 'Comment' })
vim.api.nvim_set_var('terminal_color_0', '#202632')
vim.api.nvim_set_var('terminal_color_1', '#ef7675')
vim.api.nvim_set_var('terminal_color_2', '#7db349')
vim.api.nvim_set_var('terminal_color_3', '#cd9600')
vim.api.nvim_set_var('terminal_color_4', '#50a5fa')
vim.api.nvim_set_var('terminal_color_5', '#a68cf4')
vim.api.nvim_set_var('terminal_color_6', '#00bcc0')
vim.api.nvim_set_var('terminal_color_7', '#afbbd3')
vim.api.nvim_set_var('terminal_color_8', '#202632')
vim.api.nvim_set_var('terminal_color_9', '#ef7675')
vim.api.nvim_set_var('terminal_color_10', '#7db349')
vim.api.nvim_set_var('terminal_color_11', '#cd9600')
vim.api.nvim_set_var('terminal_color_12', '#50a5fa')
vim.api.nvim_set_var('terminal_color_13', '#a68cf4')
vim.api.nvim_set_var('terminal_color_14', '#00bcc0')
vim.api.nvim_set_var('terminal_color_15', '#afbbd3')
end }
