-- do not edit manually!
return { setup = function()
vim.api.nvim_set_hl(0, 'Normal', { force = true, fg = '#5d6f92', ctermfg = 60, bg = '#f5f5f6', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'Comment', { force = true, fg = '#9da8be', ctermfg = 248 })
vim.api.nvim_set_hl(0, 'String', { force = true, fg = '#609426', ctermfg = 65 })
vim.api.nvim_set_hl(0, 'Character', { force = true, link = 'String' })
vim.api.nvim_set_hl(0, 'Constant', { force = true, fg = '#ae7800', ctermfg = 136 })
vim.api.nvim_set_hl(0, 'Identifier', { force = true, fg = '#5d6f92', ctermfg = 60 })
vim.api.nvim_set_hl(0, 'Function', { force = true, fg = '#2f86d9', ctermfg = 68 })
vim.api.nvim_set_hl(0, 'Statement', { force = true, fg = '#cd5859', ctermfg = 167, italic = true })
vim.api.nvim_set_hl(0, 'Operator', { force = true, fg = '#9da8be', ctermfg = 248 })
vim.api.nvim_set_hl(0, 'Delimiter', { force = true, link = 'Operator' })
vim.api.nvim_set_hl(0, 'Type', { force = true, fg = '#009ca2', ctermfg = 37 })
vim.api.nvim_set_hl(0, 'Special', { force = true, fg = '#5d6f92', ctermfg = 60 })
vim.api.nvim_set_hl(0, 'PreProc', { force = true, link = 'Statement' })
vim.api.nvim_set_hl(0, 'Title', { force = true, fg = '#5986b7', ctermfg = 67, bold = true })
vim.api.nvim_set_hl(0, 'Todo', { force = true, fg = '#f5f5f6', ctermfg = 255, bg = '#009ca2', ctermbg = 37, bold = true })
vim.api.nvim_set_hl(0, 'LineNr', { force = true, fg = '#d4d9e2', ctermfg = 253 })
vim.api.nvim_set_hl(0, 'CursorLineNr', { force = true, fg = '#9da8be', ctermfg = 248, bold = true })
vim.api.nvim_set_hl(0, 'Whitespace', { force = true, fg = '#d4d9e2', ctermfg = 253 })
vim.api.nvim_set_hl(0, 'CursorLine', { force = true, bg = '#eceef1', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'CursorColumn', { force = true, link = 'CursorLine' })
vim.api.nvim_set_hl(0, 'StatusLine', { force = true, fg = '#7383a2', ctermfg = 103, bg = '#f5f5f6', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'WinBar', { force = true, fg = '#7383a2', ctermfg = 103, bg = '#f5f5f6', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'WinSeparator', { force = true, fg = '#d4d9e2', ctermfg = 253 })
vim.api.nvim_set_hl(0, 'Visual', { force = true, bg = '#dbe3ec', ctermbg = 254 })
vim.api.nvim_set_hl(0, 'Search', { force = true, bg = '#c0d7f0', ctermbg = 153 })
vim.api.nvim_set_hl(0, 'CurSearch', { force = true, fg = '#f5f5f6', ctermfg = 255, bg = '#2f86d9', ctermbg = 68, bold = true })
vim.api.nvim_set_hl(0, 'Directory', { force = true, fg = '#5986b7', ctermfg = 67 })
vim.api.nvim_set_hl(0, 'MoreMsg', { force = true, fg = '#5986b7', ctermfg = 67 })
vim.api.nvim_set_hl(0, 'Question', { force = true, link = 'MoreMsg' })
vim.api.nvim_set_hl(0, 'ModeMsg', { force = true, fg = '#8290ac', ctermfg = 103 })
vim.api.nvim_set_hl(0, 'NormalFloat', { force = true, bg = '#eeeff2', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'FloatBorder', { force = true, fg = '#b3bbcc', ctermfg = 250, bg = '#f1f2f3', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'FloatTitle', { force = true, fg = '#9da8be', ctermfg = 248, bg = '#eff0f2', ctermbg = 255, bold = true })
vim.api.nvim_set_hl(0, 'Pmenu', { force = true, link = 'NormalFloat' })
vim.api.nvim_set_hl(0, 'PmenuSel', { force = true, link = 'Visual' })
vim.api.nvim_set_hl(0, 'Error', { force = true, fg = '#cd5859', ctermfg = 167, bold = true })
vim.api.nvim_set_hl(0, 'ErrorMsg', { force = true, fg = '#cd5859', ctermfg = 167, bold = true })
vim.api.nvim_set_hl(0, 'WarningMsg', { force = true, fg = '#ae7800', ctermfg = 136, bold = true })
vim.api.nvim_set_hl(0, 'DiagnosticOk', { force = true, fg = '#609426', ctermfg = 65 })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { force = true, fg = '#2f86d9', ctermfg = 68 })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { force = true, fg = '#009ca2', ctermfg = 37 })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { force = true, fg = '#ae7800', ctermfg = 136 })
vim.api.nvim_set_hl(0, 'DiagnosticError', { force = true, fg = '#cd5859', ctermfg = 167 })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk', { force = true, sp = '#609426', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { force = true, sp = '#2f86d9', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { force = true, sp = '#009ca2', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { force = true, sp = '#ae7800', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { force = true, sp = '#cd5859', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextOk', { force = true, fg = '#609426', ctermfg = 65, bg = '#e7ece4', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { force = true, fg = '#2f86d9', ctermfg = 68, bg = '#e4ebf4', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', { force = true, fg = '#009ca2', ctermfg = 37, bg = '#e0edee', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { force = true, fg = '#ae7800', ctermfg = 136, bg = '#eeeae1', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { force = true, fg = '#cd5859', ctermfg = 167, bg = '#f3e7e7', ctermbg = 255 })
vim.api.nvim_set_hl(0, 'MatchParen', { force = true, fg = '#5d6f92', ctermfg = 60, bg = '#e1e4ea', ctermbg = 254, bold = true })
vim.api.nvim_set_hl(0, 'IlluminatedWordText', { force = true, bg = '#e1e4ea', ctermbg = 254 })
vim.api.nvim_set_hl(0, 'IlluminatedWordRead', { force = true, link = 'IlluminatedWordText' })
vim.api.nvim_set_hl(0, 'IlluminatedWordWrite', { force = true, link = 'IlluminatedWordText' })
vim.api.nvim_set_hl(0, 'Added', { force = true, fg = '#609426', ctermfg = 65 })
vim.api.nvim_set_hl(0, 'Removed', { force = true, fg = '#cd5859', ctermfg = 167 })
vim.api.nvim_set_hl(0, 'Changed', { force = true, fg = '#2f86d9', ctermfg = 68 })
vim.api.nvim_set_hl(0, 'DiffAdd', { force = true, bg = '#dde7d8', ctermbg = 254 })
vim.api.nvim_set_hl(0, 'DiffDelete', { force = true, bg = '#f2dedd', ctermbg = 224 })
vim.api.nvim_set_hl(0, 'DiffChange', { force = true, bg = '#d8e5f3', ctermbg = 254 })
vim.api.nvim_set_hl(0, 'GitSignsStagedAdd', { force = true, link = 'GitSignsAdd' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChange', { force = true, link = 'GitSignsChange' })
vim.api.nvim_set_hl(0, 'GitSignsStagedDelete', { force = true, link = 'GitSignsDelete' })
vim.api.nvim_set_hl(0, 'GitSignsAddInline', { force = true, bg = '#c7d8bb', ctermbg = 187 })
vim.api.nvim_set_hl(0, 'GitSignsDeleteInline', { force = true, bg = '#eec7c5', ctermbg = 224 })
vim.api.nvim_set_hl(0, 'GitSignsChangeInline', { force = true, bg = '#c7d8bb', ctermbg = 187 })
vim.api.nvim_set_hl(0, '@attribute.builtin', { force = true, link = '@attribute' })
vim.api.nvim_set_hl(0, '@constant.builtin', { force = true, link = '@constant' })
vim.api.nvim_set_hl(0, '@function.builtin', { force = true, link = '@function' })
vim.api.nvim_set_hl(0, '@type.builtin', { force = true, link = '@type' })
vim.api.nvim_set_hl(0, '@property', { force = true, fg = '#896ed3', ctermfg = 98 })
vim.api.nvim_set_hl(0, '@variable', { force = true, fg = '#5d6f92', ctermfg = 60 })
vim.api.nvim_set_hl(0, '@variable.member', { force = true, link = '@property' })
vim.api.nvim_set_hl(0, '@keyword.vim', { force = true, link = 'Function' })
vim.api.nvim_set_hl(0, '@keyword.exception', { force = true, fg = '#8290ac', ctermfg = 103 })
vim.api.nvim_set_hl(0, '@keyword.conditional.ternary', { force = true, fg = '#8290ac', ctermfg = 103 })
vim.api.nvim_set_hl(0, '@constructor', { force = true, link = 'Function' })
vim.api.nvim_set_hl(0, '@constructor.lua', { force = true, link = 'Delimiter' })
vim.api.nvim_set_hl(0, '@string.special.url', { force = true, fg = '#2f86d9', ctermfg = 68, underline = true })
vim.api.nvim_set_hl(0, '@markup.link', { force = true, fg = '#2f86d9', ctermfg = 68 })
vim.api.nvim_set_hl(0, '@markup.link.label', { force = true, fg = '#2f86d9', ctermfg = 68, underdashed = true })
vim.api.nvim_set_hl(0, '@markup.link.url', { force = true, link = '@string.special.url' })
vim.api.nvim_set_hl(0, '@markup.quote', { force = true, fg = '#8290ac', ctermfg = 103 })
vim.api.nvim_set_hl(0, '@markup.raw', { force = true, fg = '#8678b4', ctermfg = 103 })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { force = true, fg = '#2f86d9', ctermfg = 68, bold = true })
vim.api.nvim_set_hl(0, 'TelescopeNormal', { force = true, link = 'NormalFloat' })
vim.api.nvim_set_hl(0, 'TelescopeTitle', { force = true, link = 'FloatTitle' })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { force = true, link = 'FloatBorder' })
vim.api.nvim_set_hl(0, 'CmpItemAbbr', { force = true, fg = '#7383a2', ctermfg = 103 })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { force = true, fg = '#2f86d9', ctermfg = 68, bold = true })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { force = true, fg = '#5986b7', ctermfg = 67 })
vim.api.nvim_set_hl(0, 'CmpItemKind', { force = true, fg = '#896ed3', ctermfg = 98 })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { force = true, link = 'Constant' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { force = true, link = 'Type' })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { force = true, link = 'Function' })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { force = true, link = 'Type' })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { force = true, link = 'Constant' })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { force = true, link = 'Function' })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { force = true, link = 'Type' })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { force = true, link = 'Comment' })
end }
